import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import AuthProvider from "@/component/AuthProvider/AuthProvider";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
              style={{
                backgroundColor:"#F4EEFF"	,
          // backgroundImage:
          //   "radial-gradient(at 50% 100%, rgb(156, 103, 213), rgb(220, 151, 165))",
          backgroundRepeat: "no-repeat",
          backgroundSize: "cover",
          minHeight: "100vh",
        }}
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider> {children}</AuthProvider>
      </body>
    </html>
  );
}
